---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.9.4
    app.quarkus.io/commit-id: 21fc7ed4423f158b824fc9bbec594247585358af
    app.quarkus.io/vcs-uri: https://github.com/erwinsot/Quarkus.git
    app.quarkus.io/build-timestamp: 2024-04-24 - 18:40:35 +0000
  labels:
    app.kubernetes.io/name: code-with-quarkus-pasarela
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: code-with-quarkus-pasarela
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4545
  selector:
    app.kubernetes.io/name: code-with-quarkus-pasarela
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.9.4
    app.quarkus.io/commit-id: 21fc7ed4423f158b824fc9bbec594247585358af
    app.quarkus.io/vcs-uri: https://github.com/erwinsot/Quarkus.git
    app.quarkus.io/build-timestamp: 2024-04-24 - 18:40:35 +0000
  labels:
    app.kubernetes.io/name: code-with-quarkus-pasarela
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: code-with-quarkus-pasarela
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: code-with-quarkus-pasarela
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.9.4
        app.quarkus.io/commit-id: 21fc7ed4423f158b824fc9bbec594247585358af
        app.quarkus.io/vcs-uri: https://github.com/erwinsot/Quarkus.git
        app.quarkus.io/build-timestamp: 2024-04-24 - 18:40:35 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: code-with-quarkus-pasarela
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/velkoz/code-with-quarkus-pasarela:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: code-with-quarkus-pasarela
          ports:
            - containerPort: 4545
              name: http
              protocol: TCP
